### ISSUE TITLE
Stuck at 'Establishing consensus'

### ISSUE THREAD

**Issue by rraallvv** [joewandy/coinmiq#2]
Why is the miner stuck at 'Establishing consensus' showing 0 H/s?
I'm currently using Safari on macOS.

**Comment by rraallvv** [comment]
Maybe it was something wrong from my end, it's working now.

**Comment by joewandy** [comment]
Yeah the initial sync is kind of slow because it's using the light client (which is able to mine). Once the pool mining code is merged in the Nimiq master, I will switch to using the nano pool miner -- which syncs a lot faster 😄
